export const jobData = [
  {
    company: 'Spark Studio',
    title: 'Head of Engineering',
    duration: 'March 2021 - Present',
    description: 'Led the engineering team, built a Learning Management System, developed a gamified app, and spearheaded the creation of a chat-driven learning platform using advanced AI technologies.',
    image: '/spark-studio.jpg',
    tech: 'Ruby on Rails, PostgreSQL, Next.js, AWS, Razorpay, OpenAI, DALL·E 3',
  },
  {
    company: 'BYJU\'S',
    title: 'Principal Software Engineer, Backend',
    duration: 'April 2020 – Jan 2021',
    description: 'Led the development of the BYJU\'S English Learning App, designed a conversational model, and developed a content ingestion tool.',
    image: '/byjus.jpg',
    tech: 'Dialogflow, AWS, RESTful APIs',
  },
  {
    company: 'BYJU\'S',
    title: 'Senior Software Engineer, Backend',
    duration: 'Jan 2016 – April 2020',
    description: 'Integrated the BYJU\'S App on Google Home, created a push notification framework, and developed various features including mentor scheduling and guided learning.',
    image: '/byjus.jpg',
    tech: 'Dialogflow, Firebase, AWS SQS, AWS Lambda',
  },
  {
    company: 'Housing',
    title: 'Senior Software Engineer, Backend',
    duration: 'May 2015 – Dec 2015',
    description: 'Developed a Rails engine for role-based authorization, built a microservice for user management, and worked on inventory management for online booking.',
    image: '/housing.jpg',
    tech: 'Ruby on Rails, Microservices, Inventory Management',
  },
  {
    company: 'Zynga',
    title: 'Software Engineer, Full Stack',
    duration: 'Nov 2013 – May 2015',
    description: 'Developed features for Draw Something, engaged in reverse engineering for COPPA compliance, and added new features to games.',
    image: '/zynga.jpg',
    tech: 'Marmalade (C++), Ruby on Rails',
  },
  {
    company: 'Zynga',
    title: 'Associate Software Engineer, Full Stack',
    duration: 'Feb 2012 – Oct 2013',
    description: 'Improved performance of games, added new features, and worked on templatization for feature automation.',
    image: '/zynga.jpg',
    tech: 'ActionScript, PHP',
  },
];
